### ISSUE TITLE
Terraria Tweaker 2 no legendary zenith glitch

### ISSUE THREAD

**Issue by xR0B0Xx** [TiberiumFusion/TTPlugins#2]
Its not about TTPlugins but its so stupid glich. When i dont have on TT2 i can get legendary zenith BUT when i turn on TT2 then legendary prefix just says: "see ya!" and just dissapears from my zenith. i tried FREE ITEMS: nothing. I tried SERVER COMMANDS (from other servers like /item): nothing. i tried even FORGING: of course nothing. Please tell me how do i fix this?

**Comment by TiberiumFusion** [comment]
> Its not about TTPlugins

Do not do this. This ticket is invalid and will be deleted.
